apiVersion: v1
kind: Service
metadata:
  name: connect4-service
spec:
  selector:
    type: front-end # matches the label of your pods
  ports:
    - protocol: TCP
      port: 80 # Port on the Service
      targetPort: 8000 # Port your app is listening on in the container
  type: LoadBalancer # Use NodePort if LoadBalancer isn't supported on your setup
