apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-basic-replicaset
spec:
  template:
    metadata:
      name: my-app-pod
      labels:
        type: front-end
    spec:
      containers:
        - image: nginx
          name: nginx-custom
  replicas: 6
  selector:
    matchLabels:
      type: front-end
