apiVersion: v1 # Specifies the API version for the Pod resource.
kind: Pod # Defines the resource type, which is a Pod in this case.
metadata:
  name: my-basic-pod # Metadata field that assigns a name to the Pod.
spec:
  containers:
    - image: nginx # The container image to be used. In this case, it's the default 'nginx' image.
      name: nginx-custom # Name given to the container inside the Pod for reference.

#kubectl apply -f basic_minimal_pod.yml
