apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-basic-deployment
spec:
  template:
    metadata:
      name: my-app-pod
      labels:
        type: front-end
    spec:
      containers:
        - image: nginx:1.19.0
          name: nginx-custom
  replicas: 6
  selector:
    matchLabels:
      type: front-end
